"use client";

import { useEffect, useId, useState } from "react";

/*

Renders a ```mermaid fence from MarkdownView as an actual diagram instead of a plain code block.
`mermaid` is imported dynamically inside the effect (never at module scope) because the package
touches `document`/`window` on import — a static top-level import would run during Next.js's
server-side render of this "use client" component and crash.

`mermaid.render()` returns raw SVG markup as a string, which is the library's only rendering API —
there is no "give me React elements back" option, so setting it via `dangerouslySetInnerHTML` here
is unavoidable, not a shortcut. This is lower risk than arbitrary HTML injection: the SVG is
generated by mermaid itself from Markdown that already passed through the backend's
`sanitizeMarkdownText` (see article.service.ts / TechRead equivalent), and mermaid escapes node/edge
label text into safe SVG `<text>` content rather than interpreting it as markup.

*/

interface MermaidDiagramProps {
  code: string;
}

type RenderState =
  | { status: "loading" }
  | { status: "success"; svg: string }
  | { status: "error"; message: string };

export function MermaidDiagram({ code }: MermaidDiagramProps) {
  const rawId = useId();
  const diagramId = `mermaid-${rawId.replace(/[^a-zA-Z0-9]/g, "")}`;
  const [state, setState] = useState<RenderState>({ status: "loading" });

  useEffect(() => {
    let cancelled = false;

    async function render() {
      try {
        const { default: mermaid } = await import("mermaid");
        mermaid.initialize({ startOnLoad: false, securityLevel: "strict", theme: "neutral" });
        const { svg } = await mermaid.render(diagramId, code);
        if (!cancelled) setState({ status: "success", svg });
      } catch (error) {
        if (!cancelled) {
          setState({
            status: "error",
            message: error instanceof Error ? error.message : "Failed to render diagram",
          });
        }
      }
    }

    setState({ status: "loading" });
    void render();

    return () => {
      cancelled = true;
    };
  }, [code, diagramId]);

  if (state.status === "loading") {
    return <div className="mermaid-diagram mermaid-diagram-loading">Rendering diagram…</div>;
  }

  if (state.status === "error") {
    return (
      <div className="mermaid-diagram mermaid-diagram-error">
        <p>Couldn&apos;t render this diagram ({state.message}).</p>
        <pre>
          <code>{code}</code>
        </pre>
      </div>
    );
  }

  return <div className="mermaid-diagram" dangerouslySetInnerHTML={{ __html: state.svg }} />;
}
